[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
swap_example = "9REFrpSamkX7NYhHVqoDV6ZW9pxRY5Bu5iP684pTPj2X"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
